import type { MoonTodoTheme } from "../types/settings";

export const themes: MoonTodoTheme[] = [
  {
    id: "creamVanilla",
    label: "Cream Vanilla",
    background: "from-white/95 via-amber-50/95 to-orange-50/95",
    cardBackground: "bg-white/75",
    accent: "bg-amber-300",
    text: "text-slate-900",
    mutedText: "text-amber-700/55",
    border: "border-amber-100/80",
    progress: "bg-amber-300",
    nowBackground: "bg-amber-100/85",
    nowText: "text-amber-950",
    nowMutedText: "text-amber-700/65",
    nowAccent: "bg-amber-300",
    selectedTabBackground: "bg-amber-300",
    selectedTabText: "text-amber-950",
    unselectedTabText: "text-amber-700/65 hover:text-amber-950",
  },
  {
    id: "lavenderMilk",
    label: "Lavender Milk",
    background: "from-white/95 via-violet-50/95 to-sky-50/95",
    cardBackground: "bg-white/75",
    accent: "bg-violet-300",
    text: "text-slate-900",
    mutedText: "text-violet-500/65",
    border: "border-violet-100/80",
    progress: "bg-violet-300",
    nowBackground: "bg-violet-100/85",
    nowText: "text-violet-950",
    nowMutedText: "text-violet-600/70",
    nowAccent: "bg-violet-300",
    selectedTabBackground: "bg-violet-300",
    selectedTabText: "text-violet-950",
    unselectedTabText: "text-violet-600/70 hover:text-violet-950",
  },
  {
    id: "peachSoda",
    label: "Peach Soda",
    background: "from-white/95 via-orange-50/95 to-pink-50/95",
    cardBackground: "bg-white/75",
    accent: "bg-orange-300",
    text: "text-slate-900",
    mutedText: "text-orange-500/65",
    border: "border-orange-100/80",
    progress: "bg-orange-300",
    nowBackground: "bg-orange-100/85",
    nowText: "text-orange-950",
    nowMutedText: "text-orange-600/70",
    nowAccent: "bg-orange-300",
    selectedTabBackground: "bg-orange-300",
    selectedTabText: "text-orange-950",
    unselectedTabText: "text-orange-600/70 hover:text-orange-950",
  },
  {
    id: "mintCream",
    label: "Mint Cream",
    background: "from-white/95 via-emerald-50/95 to-teal-50/95",
    cardBackground: "bg-white/75",
    accent: "bg-emerald-300",
    text: "text-slate-900",
    mutedText: "text-emerald-600/60",
    border: "border-emerald-100/80",
    progress: "bg-emerald-300",
    nowBackground: "bg-emerald-100/85",
    nowText: "text-emerald-950",
    nowMutedText: "text-emerald-700/65",
    nowAccent: "bg-emerald-300",
    selectedTabBackground: "bg-emerald-300",
    selectedTabText: "text-emerald-950",
    unselectedTabText: "text-emerald-700/65 hover:text-emerald-950",
  },
  {
    id: "babyBlue",
    label: "Baby Blue",
    background: "from-white/95 via-sky-50/95 to-blue-50/95",
    cardBackground: "bg-white/75",
    accent: "bg-sky-300",
    text: "text-slate-900",
    mutedText: "text-sky-600/60",
    border: "border-sky-100/80",
    progress: "bg-sky-300",
    nowBackground: "bg-sky-100/85",
    nowText: "text-sky-950",
    nowMutedText: "text-sky-700/65",
    nowAccent: "bg-sky-300",
    selectedTabBackground: "bg-sky-300",
    selectedTabText: "text-sky-950",
    unselectedTabText: "text-sky-700/65 hover:text-sky-950",
  },
  {
    id: "strawberryMilk",
    label: "Strawberry Milk",
    background: "from-white/95 via-rose-50/95 to-pink-50/95",
    cardBackground: "bg-white/75",
    accent: "bg-rose-300",
    text: "text-slate-900",
    mutedText: "text-rose-500/65",
    border: "border-rose-100/80",
    progress: "bg-rose-300",
    nowBackground: "bg-rose-100/85",
    nowText: "text-rose-950",
    nowMutedText: "text-rose-600/70",
    nowAccent: "bg-rose-300",
    selectedTabBackground: "bg-rose-300",
    selectedTabText: "text-rose-950",
    unselectedTabText: "text-rose-600/70 hover:text-rose-950",
  },
  {
    id: "lemonChiffon",
    label: "Lemon Chiffon",
    background: "from-white/95 via-yellow-50/95 to-lime-50/95",
    cardBackground: "bg-white/75",
    accent: "bg-yellow-300",
    text: "text-slate-900",
    mutedText: "text-yellow-700/60",
    border: "border-yellow-100/80",
    progress: "bg-yellow-300",
    nowBackground: "bg-yellow-100/90",
    nowText: "text-yellow-950",
    nowMutedText: "text-yellow-700/70",
    nowAccent: "bg-yellow-300",
    selectedTabBackground: "bg-yellow-300",
    selectedTabText: "text-yellow-950",
    unselectedTabText: "text-yellow-700/70 hover:text-yellow-950",
  },
  {
    id: "matchaLatte",
    label: "Matcha Latte",
    background: "from-white/95 via-lime-50/95 to-green-50/95",
    cardBackground: "bg-white/75",
    accent: "bg-lime-300",
    text: "text-slate-900",
    mutedText: "text-lime-700/60",
    border: "border-lime-100/80",
    progress: "bg-lime-300",
    nowBackground: "bg-lime-100/85",
    nowText: "text-lime-950",
    nowMutedText: "text-lime-700/70",
    nowAccent: "bg-lime-300",
    selectedTabBackground: "bg-lime-300",
    selectedTabText: "text-lime-950",
    unselectedTabText: "text-lime-700/70 hover:text-lime-950",
  },
];

export const defaultTheme = themes[1];
